FROM centos:7

RUN yum install epel-release -y && yum install java-11-openjdk -y
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.96/bin/apache-tomcat-8.5.96.tar.gz ./
RUN tar -xzf apache-tomcat-8.5.96.tar.gz -C /opt
WORKDIR /opt/apache-tomcat-8.5.96
COPY ./student.war webapps/student.war
ADD https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar lib/mysql-connector.jar
COPY context.xml conf/context.xml
WORKDIR ./bin

EXPOSE 8080

CMD ./catalina.sh run
